[package]
name = "wilderfolk"
version = "0.6.5-0"
description = "Wilderfolk"
authors = ["Renffr"]
license = "MIT"
# repository = ""  # omit until you have one
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-process = "2"   # needed for the Exit button if you use exit(0)

# Keep dev builds debuggable — no stripping, no abort.
[profile.dev]
opt-level = 0

# Smaller/faster release binary.
[profile.release]
strip = true
panic = "abort"
codegen-units = 1
lto = true
