/**
 * Golden-master RNG dumper — the TypeScript oracle for the Godot port.
 *
 * Emits the exact uint32 numerators behind every Mulberry32 draw so the
 * GDScript port can be compared as INTEGERS. A draw is `u32 / 2**32`, and
 * that division is exact in binary floating point, so
 * `Math.round(stream() * 4294967296)` recovers the true uint32 with zero
 * precision loss. Comparing integers removes all float-format risk.
 *
 * Uses the real simRng exports (not a reimplementation) so the fixture can
 * never drift from production behaviour.
 */
import { writeFileSync } from 'node:fs';
import { createSeededRng, hashSalt, seededRandom } from '../src/game/simRng';

const TO_U32 = 4294967296;

function u32Of(draw: number): number {
  return Math.round(draw * TO_U32);
}

const SEEDS = [1, 12345, 987654321, 4294967295];
// Real owner-stream names taken from the RNG guideline doc.
const OWNERS = ['worldGen', 'dailyPopulation', 'moonHowler', 'humanRelationships', 'rivalProfiles', '__global__'];
const DRAWS_PER_STREAM = 12;

const fixture: Record<string, unknown> = {
  note: 'Generated by scripts/dump-sim-rng.mts from src/game/simRng.ts. Integers are exact uint32 numerators; float = u32 / 2**32.',
  hashSalt: {} as Record<string, number>,
  mulberry32Advance: [] as unknown[],
  streams: {} as Record<string, number[]>,
  seededRandom: {} as Record<string, number>,
};

// 1. FNV-1a owner salts.
const saltTable = fixture.hashSalt as Record<string, number>;
for (const owner of OWNERS) saltTable[owner] = hashSalt(owner);

// 2. Raw advance steps, to isolate the (s + 0x6d2b79f5) >>> 0 step.
const advanceTable = fixture.mulberry32Advance as unknown[];
for (const seed of [0, 1, 12345, 4294967295]) {
  const steps: number[] = [];
  let s = seed >>> 0;
  for (let i = 0; i < 6; i++) {
    s = (s + 0x6d2b79f5) >>> 0;
    steps.push(s);
  }
  advanceTable.push({ start: seed >>> 0, states: steps });
}

// 3. Per-owner stream sequences — the real thing the simulation draws from.
const streamTable = fixture.streams as Record<string, number[]>;
for (const seed of SEEDS) {
  for (const owner of OWNERS) {
    const rng = createSeededRng(seed, owner);
    const values: number[] = [];
    for (let i = 0; i < DRAWS_PER_STREAM; i++) values.push(u32Of(rng()));
    streamTable[`${seed}|${owner}`] = values;
  }
}

// 4. Stateless one-shot rolls.
const seededTable = fixture.seededRandom as Record<string, number>;
for (const seed of SEEDS) {
  for (const owner of OWNERS) seededTable[`${seed}|${owner}`] = u32Of(seededRandom(seed, owner));
}

// 5. Sanity: two streams must differ, and the same call must be reproducible.
const repro = u32Of(createSeededRng(12345, 'worldGen')());
const first = (streamTable['12345|worldGen'] as number[])[0];
if (repro !== first) throw new Error(`oracle self-check failed: ${repro} !== ${first}`);

const json = JSON.stringify(fixture, null, 2);

/**
 * Write the fixture from Node in UTF-8. Do NOT rely on shell redirection:
 * Windows PowerShell 5.1's `>` emits UTF-16LE (BOM FF FE), which Godot's
 * FileAccess reads as NUL-interleaved bytes and fails to JSON-parse.
 */
const target = process.argv[2] ?? '../Wilderfolk2/tests/fixtures/sim_rng_golden.json';
writeFileSync(target, json + '\n', 'utf8');

console.log(`wrote ${target}`);
console.log(`streams: ${Object.keys(streamTable).length}, bytes: ${json.length}`);
